### ISSUE TITLE
PlayerEx New Functions .json format

### ISSUE THREAD

**Issue by Hojew** [CleverNucleus/PlayerEx#102]
Hey there! These are my configs. You can kinda see what I am going for but yeah its just not working when I try to run it "Not validated". Please let me know if you need more info

![Config](https://user-images.githubusercontent.com/122690319/212484863-20c369eb-7e14-4e24-a928-5f4816893c1a.jpg)
![Config 2](https://user-images.githubusercontent.com/122690319/212485282-97d05126-0bc9-4785-84e4-159386858980.jpg)

**Comment by Hojew** [comment]
Okay So I actually got a valid .json file. I guess I just needed to hit tab and "}" more... but after it was validated the whole game crashed? I will attach the crash report below. maybe you can help me!
[Crash report.pdf](https://github.com/CleverNucleus/PlayerEx/files/10418470/Crash.report.pdf)

**Comment by CleverNucleus** [comment]
Hi there,
The original issue was due to incorrect JSON formatting - as you correctly stated in your later comment, you were missing `}` in some places.

The subsequent crash report looks like it is still due to incorrect JSON data. Would you be able to show me the JSON file that was validated?
Thanks.

**Comment by Hojew** [comment]
Hey! here is the JSON file. Thanks!
[function 2.0.pdf](https://github.com/CleverNucleus/PlayerEx/files/10418599/function.2.0.pdf)

**Comment by CleverNucleus** [comment]
Hi,
Your file still has formatting issues like missing brackets. I have created a correctly formatted one for you: [functions.json.txt](https://github.com/CleverNucleus/PlayerEx/files/10418846/functions.json.txt).

I have noticed a small bug with how PlayerEx is displaying some of the attribute bonuses for Intelligence/Luckiness. You may see that skilling Intelligence says it will provide `+1000%` Heal Amplification. This is only a visual bug - it is still just providing `+1%` - this is similarly the case with some other attributes; just thought I'd give you the heads up for this one, since it was thanks to your issue that I noticed it. Hopefully I will have it fixed soon.
Thanks.

**Comment by Hojew** [comment]
Got it! Thanks for your help!!
