### ISSUE TITLE
[Suggestion] Locking progression behind levels

### ISSUE THREAD

**Issue by DanMeadWasTaken** [CleverNucleus/PlayerEx#110]
Similar to how [reskillable ](https://www.curseforge.com/minecraft/mc-mods/reskillable) was able to lock items behind skill levels. As a config option turned off by default- and using a list of user created requirements for items they wish to add requirements to. 

So, an example would be:
      to use a diamond sword you'd have to have strength 10
      
This is mostly an idea targeted towards mod-pack creators making a pack which is trying to stretch out the game-play a little- like for example on a server, stopping a player from just obtaining end-game gear right away

**Comment by CleverNucleus** [comment]
Hi there,
I appreciate your suggestion! I've had a few people request this - however, I will probably not be adding this any time soon, if at all on PlayerEx. I feel that if this feature were to be implemented, it should probably be an addon mod. Indeed, I've exposed the relevant functionality in the PlayerEx API with this in mind, so that anyone can develop an addon. 
Thanks.

**Comment by DanMeadWasTaken** [comment]
Hmmm, alright, so basically the groundwork is there, just waiting for someone to make the addon?

Also, sorry, i looked through the closed ones to see if someone hadn't mentioned the idea before but didn't see anything
