### ISSUE TITLE
How to detect when player levels up?

### ISSUE THREAD

**Issue by tallubhai** [CleverNucleus/PlayerEx#140]
I'm creating a modpack and I wish to set up a quest via ftb quests, that will reward the player with xp the first time they level themselves up. How do I detect when a player's level increases?

**Comment by CleverNucleus** [comment]
Hi there,
From a modding perspective, you can use [this](https://github.com/CleverNucleus/data-attributes/blob/cf265716f867b30206e08c09badbb459ffbf3bc9/src/main/java/com/github/clevernucleus/dataattributes/api/event/EntityAttributeModifiedEvents.java#L24) event from Data Attributes.

Otherwise, I'm not sure - if there are any ways to detect when the value of an attribute changes (i.e., with command blocks), this would also work since player level is just another attribute.

Hope that helps,
Thanks.
