### ISSUE TITLE
Game crash on Mac

### ISSUE THREAD

**Issue by FroggDogg** [CleverNucleus/PlayerEx#26]
So, with removing all mods (which is about 84 I believe)  besides the required ones (which from what I can understand is only data-attributes and playerex) the game crashes when trying to launch. I cannot find anything online about how to solve this or even any others having this same issue. 

I have tried different versions of fabric and different versions of data-attributes and playerex and none of them work. Does playerex just not work on Mac? If I am mistaken than please lmk. I have attached the error message below.
<img width="752" alt="Screen Shot 2021-09-15 at 12 19 23 AM" src="https://user-images.githubusercontent.com/88856065/133380945-c2510f8d-663f-408f-9214-93dd248bebaf.png">

**Comment by CleverNucleus** [comment]
Hi there,
Since I don't have access to a mac to test on and there is no crash report, I can only recommend the *exact* versions for everything:

 - make sure that you're running Java 16 or above;
 - use Fabric Loader 0.11.6 or above;
 - use Fabric API 0.37.1 or above;
 - use Data Attributes 1.0.1 or above;
 - use PlayerEx 3.0.3.
 
 I've verified that I'm not using anything from `java.awt`, which can sometimes be missing from Macs.
 Other than that, I cannot help much more with the information available.

**Comment by CleverNucleus** [comment]
Closing this because I have no way of knowing if I've fixed it; and development cycle for a mac is too slow if I don't personally have one.
