### ISSUE TITLE
Server/Client incompatibilities?

### ISSUE THREAD

**Issue by MonkeyPrime123** [CleverNucleus/PlayerEx#41]
There are no issues with incompatibilities with the mod itself, but when I try to log onto a private server, I get the message saying that the server needs data attributes 1.0.6 even though I have it inside of my mods folder. is it supposed to be somewhere else?

**Comment by CleverNucleus** [comment]
Hi there,
Do you have Data Attributes v1.0.6 installed on both the client and the server? If you are receiving the message _"Disconnected: server requires client to have Data Attributes version 1.0.6."_, then this is a sign that the client does not have Data Attributes installed. 
Thanks.

**Comment by MonkeyPrime123** [comment]
I copied the files exactly from my mods folder to the mods folder on the server. The mod was also working on single-player mode.

**Comment by CleverNucleus** [comment]
I am interpreting the fact that it is working on single player as verification that you have installed it on your client. If you have indeed copied the same file over and installed it on the server, then the issue is likely not with Data Attributes. The disconnection message you get is definitely: _"Disconnected: server requires client to have Data Attributes version 1.0.6."_ yes? Confirming this greatly helps diagnosing this issue. 

Try running the server/client with only Fabric API and Data Attributes and see if you still get the same issue. If not, try again but with PlayerEx additionally installed. 

Additionally, it would be useful to know if you are running a lot of mods/datapacks - if so then the issue may be login packets are too big - see [this](https://www.curseforge.com/minecraft/mc-mods/xl-packets-fabric) mod. Until I have more information I cannot provide further help.

**Comment by MonkeyPrime123** [comment]
Yes, that is the message that I am getting when disconnected. I am using mine-hut as a hosting service, and to be more specific, every time I try to log onto the server, I am just met with that message. As far as I know, the world loads and everything as well, I am just immediately disconnected when the world is finished loading. I just tried joining the server after changing the mods, both client and server-side to only fabric API and data attributes. I also tried downloading the mod you suggested. It does not seem to be working. 
These are the mods I have been running. 

![modsforinquiry](https://user-images.githubusercontent.com/96602527/147376711-74592c24-2782-44c1-bc90-f36c8be17584.PNG)

**Comment by CleverNucleus** [comment]
I've done some testing, but I can't seem to replicate this issue. I've verified that the mod works as intended with both local and external server hosting. If you have indeed gone through the diagnostic steps mentioned previously and the issue has persisted that makes me think the issue is with networking. The only thing that can cause this disconnect message is if the client is not understanding the server's login packets.

You could try running just Origins and its dependencies (without DataAttributes) and see if you get a similar message? Origins and DataAttributes use more or less the same [login code](https://github.com/apace100/origins-fabric/blob/20e1b5133cf76c450ed26ec9332a9dad2737e7b7/src/main/java/io/github/apace100/origins/networking/ModPacketsC2S.java#L122). If you do, then the issue is not with your mods but with your networking. Other than that though I have no idea what is causing your issue.
