### ISSUE TITLE
Request - Config option to hide/disable additional inventory tabs

### ISSUE THREAD

**Issue by floral-qua-floral** [CleverNucleus/PlayerEx#47]
I'm thinking of using PlayerEx for the super useful attributes it adds rather than its leveling system, since they can be manipulated with things such as datapacks or KubeJS scripts. It's easy to configure the level-up formula to require obscene amounts of XP, which effectively disables the leveling system, but that leaves the two tabs in the inventory which are no longer relevant - so it'd be really nice to have a way to just make them not show up.

**Comment by CleverNucleus** [comment]
Hi there,
This is an interesting suggestion, I can definitely see the use in being able to disable the tabs. Note that there is also a hotkey (`R` by default) that opens the attributes screen. What I can do is make a server-side config option to disable access to the attributes screen and hide the inventory tabs. Please advise if there is any specific implementation you had in mind, otherwise I'll just go with the aforementioned. 

I'll leave this open until I output a release containing something to this effect.
Thanks.

**Comment by floral-qua-floral** [comment]
Thanks! Just a simple server-side toggle sounds like it'd be perfect. Also, I didn't even notice there was a hotkey during my testing, so thank you for pointing that out!

**Comment by CleverNucleus** [comment]
With version 3.1.4 implemented:
 - Server side config option to disable access to attributes screen (disable hotkey and hide tabs).
Thanks.
