### ISSUE TITLE
[Suggestion] Dark mode GUI

### ISSUE THREAD

**Issue by Timolino456** [CleverNucleus/PlayerEx#53]
As with all mods that change GUI, it looks kind of bad with resource packs.
I believe the "dark mode" that a couple of vanilla style resource packs (e.g. Vanilla Tweaks) use and the GUI changing mods that support one, all use the same grey tones.
It would be nice if you added an option in the Mod Menu for enabling a dark mode that changes the mod's GUI to these same colors. It would be applied to all three GUI windows, the latter two would then have a dark grey border instead of the vanilla white/light grey one, the normal inventory GUI window would just have to be adjusted.
Here's a screenshot of the inventory GUI for reference:
![2022-02-23_11 14 40](https://user-images.githubusercontent.com/38137599/155299978-13d448dd-9f9b-4c9f-bf4e-fb4e79846e2a.png)

These are the hex codes for the grey tones to save you some time if you decide to do it:
Light grey: 6b6b6b
Medium grey: 535353
Dark grey: 333333

**Comment by CleverNucleus** [comment]
Hi there,
I like this suggestion, it's easy to implement so I'll include it in the next release.
Thanks.

**Comment by CleverNucleus** [comment]
Hi there,
I've made assets for dark mode available [here](https://github.com/CleverNucleus/PlayerEx/tree/master/util/darkmode). Since there are many different "dark mode" gui resource packs, I've used the colours specific to Vanilla Tweaks > GUI > Dark UI pack.

You can include the aforementioned assets in a resource pack to have PlayerEx in dark mode. This makes more sense than implementing extra textures in the mod and another config option.
Thanks.

**Comment by Balakay420** [comment]
@CleverNucleus hey! the gui.png asset you mentioned above is missing the buttons and icons

**Comment by Balakay420** [comment]
![gui](https://user-images.githubusercontent.com/106470691/175885329-f32c6182-bd52-46c8-9106-05be6d6a0ad7.png)
There i fixed it :)

**Comment by CleverNucleus** [comment]
Hi there @Balakay420,
Thanks for catching that for me, I've now uploaded the fixed gui.png asset.
