### ISSUE TITLE
Will 1.19.1 be supported in the future?

### ISSUE THREAD

**Issue by xiaoxiang-7** [CleverNucleus/PlayerEx#84]

**Comment by CleverNucleus** [comment]
No, 1.19.1. won't be supported. This is based on the following rationale:

- I understand people staying on 1.18.2, as 1.19 was a fairly inconsequential update for many, therefore I will continue to maintain long-term support for 1.18.2. Additionally, it is the version I personally like the best at the moment.
- I understand people staying on 1.19, as it was the last gameplay update _and_ the last update before chat reporting, therefore I will output releases for this version were I can.
- I understand people staying on 1.19.2, as it is the latest version of the game and the latest version of the game will almost always be supported. I am only supporting 1.19.2 because it is the latest - as soon as 1.19.3 or 1.20 comes along, support for 1.19.2 will be dropped.
- Given the aforementioned statements, there is no reason for any mod to continue supporting 1.19.1. It provides nothing over 1.19 except chat reporting, and is no longer the latest version. The same could similarly be said for 1.18.1 or 1.17.

I hope that helps,
Thanks.

**Comment by xiaoxiang-7** [comment]
Got it, thanks for the reply.
