### ISSUE TITLE
Tool stats display incorrectly

### ISSUE THREAD

**Issue by Kuggle01** [CleverNucleus/PlayerEx#89]
The stats of every tool in the game (spefically the attack speed) displays incorrectly 
![Minecraft_ 1 19 2 10_17_2022 5_59_05 PM](https://user-images.githubusercontent.com/77563171/196291758-ad84a084-2724-451b-a698-4a7f18c95e27.png)
Annoyingly, this also overrides mods that change the display of tool/weapon stats such as https://www.curseforge.com/minecraft/mc-mods/tool-stats

**Comment by CleverNucleus** [comment]
Hi there,
PlayerEx modifies tool stats to display Attack Speed and Attack Damage the same way all other attributes are displayed - in blue and red with positive and negative modifiers. Furthermore, the values you see are not incorrect. By default, Minecraft displays what your Attack Damage/Speed will be *when the tool is equipped*; that is to say, the final value is displayed. PlayerEx changes this to display the *change in value* - or rather, how the tool will affect the player. Note how in default Minecraft there is no `+` or `-`.

This is, naturally, not to everyone's liking; and can be a source of incompatibility between other mods that modify item tooltips, such as Tool Stats. That's why it can be configured in the mod's client config. Please see [here](https://clevernucleus.github.io/playerex-1.18.2_content.html#config) for more information.

You have three config options:
- `PLAYEREX` which is as described above.
- `VANILLA` which displays the tooltip in the familiar green *final* value, but fixes a bug with default Minecraft that causes Attack Damage/Speed to not account for attribute modifiers.
- `DEFAULT` which completely disables any modification of the tooltip by PlayerEx, and is implemented for cases such as yours where another mod is present that modifies the tooltip.

Hope that helps,
Thanks.
